### ISSUE TITLE
[idea] Move scroll bar

### ISSUE THREAD

**Issue by zax71** [jadeposting/gatekeep#1]
The scroll bar was moved in 1.19.1 and i think it would be within scope of this mod to move to back to the left.

**Comment by jadeposting** [comment]
finally got around to this, sorry for the nearly 2 year wait lmao
will be coming with 1.3.0/minecraft 1.20.5 since i'm gonna need to update the mod regardless

**Comment by zax71** [comment]
Ooh! Thanks for looking at this :D I’ll ~~patiently~~ wait for then!

**Comment by jadeposting** [comment]
closed as of https://github.com/jadeposting/gatekeep/releases/tag/1.3.0 - ~modrinth will take >1h to update their stuff for 1.20.5 so it'll be uploaded there later. jar can be found in the github release for now~
edit: it's up on modrinth now
