### ISSUE TITLE
[Bug] Chat Box background missing 1.19.3

### ISSUE THREAD

**Issue by zax71** [jadeposting/gatekeep#2]
Version 1.1.2

Upon loading the mod and opening chat in 1.19.3 the background is missing

**Comment by jadeposting** [comment]
fixed in https://github.com/mikuflap/gatekeep/commit/d0cda206250e4d91733ac0226fea2410af4f1e11
release can be downloaded [here](https://github.com/mikuflap/gatekeep/releases/tag/1.1.3)
