### ISSUE TITLE
Crash on 1.20

### ISSUE THREAD

**Issue by Rozbiynk** [jadeposting/gatekeep#3]
crash report - https://mclo.gs/Oezrz3B
seem it conflicting with every mod that have pop out. For example death log, item swapper, plasmo voice
https://mclo.gs/XxwNnpX
https://mclo.gs/AbvT2EY

**Comment by jadeposting** [comment]
please try https://github.com/jadeposting/gatekeep/releases/tag/1.2.1 & let me know, only mod i could reproduce this with was shutupmojang but i'm also not using quilt so i'm not sure if that's another factor

**Comment by Rozbiynk** [comment]
bruh can you compile it please?

**Comment by Rozbiynk** [comment]
and on 1.2.0 it crash without shutupmojangs too

**Comment by Rozbiynk** [comment]
okay i do this itself and its still crashes (shut up mojang disabled)
latest log https://mclo.gs/qeKkj7l
crash report https://mclo.gs/YtFXPnj

**Comment by jadeposting** [comment]
> bruh can you compile it please?

very sorry, i did not realize that i didnt upload the jar

approached a different method of resolving this with https://github.com/jadeposting/gatekeep/commit/022c31bedfec38c9553b4657a9d3e7e66939eae0 & actually uploaded the jar this time, same link as before, so give that a try

**Comment by Rozbiynk** [comment]
latest log https://mclo.gs/P92EMiA
crash log https://mclo.gs/WwtPAeW

**Comment by Rozbiynk** [comment]
seems error is quite different

**Comment by jadeposting** [comment]
you're running 2 mods that all do the same thing as gatekeep (shutupmojang, and chatsigninghider), in this case it's chat signing hider so you can go ahead and remove that (shutupmojang is fine to keep as it does an extra thing that the other two don't do)

**Comment by Rozbiynk** [comment]
if i disable these 2 mod everything is fine, thanks
