### ISSUE TITLE
Network Protocol Error

### ISSUE THREAD

**Issue by AllOutJay** [jadeposting/gatekeep#4]
Information
Minecraft version: 1.21
Modloader: Fabric
Fabric loader version: 0.16.0
Environment: Multiplayer

Mod name: gatekeep
Mod version: gatekeep-1.3.0.jar

Description
When logging into any server with just the Fabric API and gatekeep installed on the client, I receive a Network Protocol Error.

Crash report
[Minecraft Network Protocol Error Report](https://mclo.gs/y7EW9MA)

**Comment by jadeposting** [comment]
fixed with 1.3.1 which can be downloaded here https://github.com/jadeposting/gatekeep/releases/tag/1.3.1 or on modrinth https://modrinth.com/mod/gatekeep/version/1.3.1
